/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alex.Ka. (https://sketchfab.com/Alex.Ka.)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/honda-shadow-rs-2010-2e7cf7bc195044f4a0f60c04581e2691
title: Honda Shadow RS 2010
*/

import React, { useRef, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import styled from "styled-components";
import { flex } from "../../Global.styles";

const Hobbie = styled.div`
  ${flex}
  background-color: rgb(0,0,0,0.7);
  padding: 10px 20px;
  border: 1px solid white;
  color: white;
  margin-top: -200px;
  margin-left: -70px;
  transform: translateY(30px);
    opacity: 0;
    transition: all .7s ease-out;
`;

const HobbieWrap = styled.div`
  .showing {
    transform: translateY(0);
    opacity: 1;
  }
`;

export function Honda(props) {
  const { nodes, materials } = useGLTF("/honda_shadow_rs_2010.glb");
  const [hovered, setHovered] = useState(false);
  
  return (
    <group
      {...props}
      dispose={null}
      onPointerEnter={() => {
        setHovered(true);
      }}
      onPointerLeave={() => {
        setHovered(false);
      }}
    >
      <Html>
        <HobbieWrap>
          <Hobbie className={hovered ? 'showing' : null}>Motorcycle</Hobbie>
        </HobbieWrap>
      </Html>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={hovered ? 1.1 : 1}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Honda_Shadow_RS_2010_by_Alex_Ka}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.aluminiumdetails}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.black_chrome}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.black_mate}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.black_plastic}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.brakelight}
        />
        <mesh geometry={nodes.Object_8.geometry} material={materials.chrome} />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.chromedetails}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.headlight}
        />
        <mesh geometry={nodes.Object_11.geometry} material={materials.hondaF} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.hondaR} />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.matedetails}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.mirrors}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.plasticdetails}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.sidereflectors}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.spdglass}
        />
        <mesh geometry={nodes.Object_18.geometry} material={materials.tire} />
      </group>
    </group>
  );
}

useGLTF.preload("/honda_shadow_rs_2010.glb");
