/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SideQuest (https://sketchfab.com/sidequest)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sydney-apartment-night-custom-home-07da6393b6434adcb74023858d858ec6
title: Sydney Apartment (Night) - Custom Home
*/

import React, { useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import Box from "./Box";
import styled from "styled-components";
import { flex } from "../../Global.styles";
import { BsSearch } from "react-icons/bs";
import AnimSphere from "./AnimSphere";
import { Honda } from "./Honda";
import { Xbox } from "./Xbox";
import { Banana } from "./Banana";

const BtnLook = styled.div`
  background-color: rgb(0, 0, 0, 0.7);
  color: white;
  font-weight: bold;
  width: max-content;
  ${flex}
  border-radius: 5px;
  border: 1px solid white;
  cursor: pointer;
  transition: all 0.3s ease-out;
  padding: 10px 20px;
  z-index: 0;

  &:hover {
    color: black;
    background-color: white;
  }
`;

const Content = styled.div`
  ${flex}
  color: white;
  background-color: rgb(0, 0, 0, 0.7);
  padding: 20px;
  border-radius: 20px;
  flex-direction: column;
  width: max-content;

  span {
    margin-top: 20px;
    font-weight: bold;
    font-size: 1.5rem;
  }

  span:first {
    margin-top: unset;
  }
`;

const Room = (props) => {
  const { nodes, materials } = useGLTF("/room.glb");
  const [position, setPosition] = useState([2.5, -1.5, 1.5]);

  return (
    <group {...props} dispose={null} position={position}>
      <group position={[1, 2, -3]} scale={[0.1, 0.1, 0.1]}>
        <Html>
          <BtnLook
            onClick={() => {
              setPosition([0, -1.5, 2]);
            }}
            id="TV"
          >
            <BsSearch/>
          </BtnLook>
        </Html>
      </group>
      <group position={[2, 2, 0]} scale={[0.1, 0.1, 0.1]}>
        <Html>
          <BtnLook
            onClick={() => {
              setPosition([-1, -1.5, 0]);
            }}
            id="corner"
          >
            <BsSearch />
          </BtnLook>
        </Html>
      </group>
      <group position={[-5, 2, 0]} scale={[0.1, 0.1, 0.1]}>
        <Html>
          <BtnLook
            onClick={() => {
              setPosition([5, -1.5, 0.5]);
            }}
            id="table"
          >
            <BsSearch />
          </BtnLook>
        </Html>
      </group>
      <group position={[-2.5, 3, -1.5]} scale={[0.1, 0.1, 0.1]}>
        <Html>
          <BtnLook
            onClick={() => {
              setPosition([2.5, -1.5, 1]);
            }}
            id="middle"
          >
            <BsSearch />
          </BtnLook>
          {/* <Content>
            <span>El miri Younes</span>
            <span>Junior Web Developer</span>
          </Content> */}
        </Html>
      </group>
      <group position={[1, 0.75, -3.3]} scale={[0.5, 0.5, 0.5]}>
        <group position={[0, 0, 0]} scale={[1, 1, 1]}>
          <Xbox />
        </group>
      </group>
      <group position={[-5, 1.5, -1]} scale={[0.1, 0.1, 0.1]}>
        <mesh>
          <AnimSphere />
        </mesh>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI, 0, -Math.PI]}>
            <group
              position={[0.37, 0.26, 3.21]}
              rotation={[0, Math.PI / 2, 0]}
              scale={0.16}
            >
              <mesh
                geometry={nodes.Object_5.geometry}
                material={materials.Material_1168}
              />
            </group>
            <group
              position={[5.92, 0.1, 2.81]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[0.2, 0.16, 0.16]}
            >
              <group position={[0, 10, 0]}></group>
              <mesh
                geometry={nodes.Object_7.geometry}
                material={materials.Material_1175}
              />
            </group>
            <group
              position={[-1.52, 3.44, 1.59]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[0.28, 0.16, 0.28]}
            >
              <mesh
                geometry={nodes.Object_9.geometry}
                material={materials.Material_1180}
              />
            </group>
            <group
              position={[-0.28, 0.45, 1.23]}
              rotation={[0, Math.PI / 2, 0]}
              scale={0.16}
            >
              <mesh
                geometry={nodes.Object_11.geometry}
                material={materials.Material_1169}
              />
            </group>
            <group
              position={[0.57, 0.59, -0.35]}
              rotation={[1.22, 1.57, 0]}
              scale={[0.27, 0.22, 0.27]}
            >
              <mesh
                geometry={nodes.Object_13.geometry}
                material={materials.Material_1183}
              />
            </group>
            <group
              position={[-2.75, -0.03, 2.59]}
              rotation={[0, Math.PI / 2, 0]}
              scale={0.16}
            >
              <mesh
                geometry={nodes.Object_15.geometry}
                material={materials.Material_1181}
              />
            </group>
            <group
              position={[2.72, -0.02, 3.58]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[0.5, 0.16, 0.71]}
            >
              <mesh
                geometry={nodes.Object_17.geometry}
                material={materials.Material_1163}
              />
            </group>
            <group
              position={[2.72, -0.02, 3.58]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[0.5, 0.16, 0.71]}
            >
              <mesh
                geometry={nodes.Object_19.geometry}
                material={materials.Material_1161}
              />
            </group>
            <group
              position={[5.92, 1.44, 0.12]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={0.66}
            >
              <mesh
                geometry={nodes.Object_21.geometry}
                material={materials.Material_1167}
              />
            </group>
            <group
              position={[1.61, 0.54, 3.46]}
              rotation={[0, Math.PI / 2, 0]}
              scale={1.06}
            >
              <mesh
                geometry={nodes.Object_23.geometry}
                material={materials.Material_1184}
              />
            </group>
            <group
              position={[0.37, 0.26, 3.21]}
              rotation={[0, Math.PI / 2, 0]}
              scale={0.16}
            >
              <mesh
                geometry={nodes.Object_25.geometry}
                material={materials.Material_1166}
              />
            </group>
            <group
              position={[5.95, 0.94, 0.77]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[0.12, 0.12, 0.09]}
            >
              <mesh
                geometry={nodes.Object_27.geometry}
                material={materials.Material_1179}
              />
            </group>
            <group
              position={[-0.28, 0.45, 1.23]}
              rotation={[0, Math.PI / 2, 0]}
              scale={0.16}
            >
              <mesh
                geometry={nodes.Object_29.geometry}
                material={materials.Material_1164}
              />
            </group>
            <group position={[5.22, 0.92, 0.59]} scale={0.94}>
              <mesh
                geometry={nodes.Object_31.geometry}
                material={materials.Material_1173}
              />
            </group>
            <group
              position={[-2.38, 0.45, -0.73]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[0.94, 0.65, 0.94]}
            >
              <mesh
                geometry={nodes.Object_33.geometry}
                material={materials.Material_1177}
              />
            </group>
            <group
              position={[2.72, -0.02, 3.58]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[0.12, 0.12, 0.09]}
            >
              <mesh
                geometry={nodes.Object_35.geometry}
                material={materials.Material_1182}
              />
            </group>
            <group
              position={[2.72, -0.02, 3.58]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[0.5, 0.16, 0.71]}
            >
              <mesh
                geometry={nodes.Object_37.geometry}
                material={materials.Material_1162}
              />
            </group>
            <group
              position={[2.83, 0.29, 3.6]}
              rotation={[0, Math.PI / 2, 0]}
              scale={0.92}
            >
              <mesh
                geometry={nodes.Object_39.geometry}
                material={materials.Material_1197}
              />
            </group>
            <group position={[2.72, -0.02, 3.58]}>
              <mesh
                geometry={nodes.Object_41.geometry}
                material={materials.Material_1170}
              />
            </group>
            <group position={[2.72, -0.02, 3.58]}>
              <mesh
                geometry={nodes.Object_43.geometry}
                material={materials.Material_1165}
              />
            </group>
            <group
              position={[4.44, 1.06, 3.55]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.83, 1, 0.87]}
            >
              <mesh
                geometry={nodes.Object_45.geometry}
                material={materials.Material_1172}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/room.glb");

export default Room;
