/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Allen.Michael (https://sketchfab.com/Allen.Michael)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/shoes-test-f41910b590be4ab0b9eb058728279229
title: shoes_test
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Shoe = (props) => {
  const group = useRef();
  const [color, setColor] = useState()
  const { nodes, materials, animations } = useGLTF(`${window.location.hostname.substring(0,9) === "localhost" ? '/' : '/ThreeJS/'}shoes_test.glb`);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions !== undefined && Object.values(actions)[0].play();
  }, []);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.09}
      position={[0, 0.5, 0]}
    >
      <group name="Sketchfab_Scene" scale={0.1}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="c6af984a3aae410e98f51ec7c66deb1efbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Shoe_Anim">
                  <group
                    name="detalle_lengueta_low"
                    position={[0.74, 101.36, 130.6]}
                  >
                    <mesh
                      name="detalle_lengueta_low_lambert16_0"
                      geometry={nodes.detalle_lengueta_low_lambert16_0.geometry}
                      material={materials.lambert16}
                      material-color={props.color}
                    />
                  </group>
                  <group name="Cara_der_low" position={[-28.84, 69.34, 95.39]}>
                    <mesh
                      material-color={props.color}
                      name="Cara_der_low_lambert3_0"
                      geometry={nodes.Cara_der_low_lambert3_0.geometry}
                      material={materials.lambert3}
                    />
                  </group>
                  <group name="Corte_1_low" position={[-9.47, 26.64, 184.31]}>
                    <mesh
                      material-color={props.color}
                      name="Corte_1_low_lambert4_0"
                      geometry={nodes.Corte_1_low_lambert4_0.geometry}
                      material={materials.lambert4}
                    />
                  </group>
                  <group name="corte_2_low" position={[-7.84, 45.56, 189.71]}>
                    <mesh
                      material-color={props.color}
                      name="corte_2_low_lambert12_0"
                      geometry={nodes.corte_2_low_lambert12_0.geometry}
                      material={materials.lambert12}
                    />
                  </group>
                  <group name="cara_izq_low" position={[23.55, 66.32, 96.17]}>
                    <mesh
                      material-color={props.color}
                      name="cara_izq_low_lambert2_0"
                      geometry={nodes.cara_izq_low_lambert2_0.geometry}
                      material={materials.lambert2}
                    />
                  </group>
                  <group name="corte_3_low" position={[0.9, 62.16, 168.21]}>
                    <mesh
                      material-color={props.color}
                      name="corte_3_low_lambert6_0"
                      geometry={nodes.corte_3_low_lambert6_0.geometry}
                      material={materials.lambert6}
                    />
                  </group>
                  <group name="Burbuja_low">
                    <mesh
                      name="Burbuja_low_blinn10_0"
                      geometry={nodes.Burbuja_low_blinn10_0.geometry}
                      material={materials.blinn10}
                    />
                  </group>
                  <group
                    name="corte_trasero_inf_low"
                    position={[-6.82, 56.24, 43.18]}
                  >
                    <mesh
                      material-color={props.color}
                      name="corte_trasero_inf_low_lambert18_0"
                      geometry={
                        nodes.corte_trasero_inf_low_lambert18_0.geometry
                      }
                      material={materials.lambert18}
                    />
                    <mesh
                      material-color={props.color}
                      name="corte_trasero_inf_low_lambert18_0_1"
                      geometry={
                        nodes.corte_trasero_inf_low_lambert18_0_1.geometry
                      }
                      material={materials.lambert18}
                    />
                  </group>
                  <group name="Suela_Up_low" position={[-9.5, 14.11, 138.31]}>
                    <mesh
                      name="Suela_Up_low_blinn11_0"
                      geometry={nodes.Suela_Up_low_blinn11_0.geometry}
                      material={materials.blinn11}
                    />
                  </group>
                  <group name="Suela_low" position={[-9.46, 2.1, 138.93]}>
                    <mesh
                      name="Suela_low_lambert13_0"
                      geometry={nodes.Suela_low_lambert13_0.geometry}
                      material={materials.lambert13}
                    />
                  </group>
                  <group
                    name="Agujetas_low"
                    position={[1.4, 71.15, 161.03]}
                    scale={[0.98, 1, 1]}
                  >
                    <mesh
                      name="Agujetas_low_lambert9_0"
                      geometry={nodes.Agujetas_low_lambert9_0.geometry}
                      material={materials.lambert9}
                    />
                    <mesh
                      name="Agujetas_low_lambert9_0_1"
                      geometry={nodes.Agujetas_low_lambert9_0_1.geometry}
                      material={materials.lambert9}
                    />
                  </group>
                  <group name="group1" position={[-0.46, 85.06, 47.49]}>
                    <group
                      name="Grosor_Superior_Trasero_low"
                      position={[-0.45, 6.64, 0.43]}
                    >
                      <mesh
                        name="Grosor_Superior_Trasero_low_lambert17_0"
                        geometry={
                          nodes.Grosor_Superior_Trasero_low_lambert17_0.geometry
                        }
                        material={materials.lambert17}
                      />
                    </group>
                    <group
                      name="corte_trasero_superior_low"
                      position={[0, -0.97, 0]}
                    >
                      <mesh
                        material-color={props.color}
                        name="corte_trasero_superior_low_lambert14_0"
                        geometry={
                          nodes.corte_trasero_superior_low_lambert14_0.geometry
                        }
                        material={materials.lambert14}
                      />
                    </group>
                  </group>
                  <group name="group2" position={[0.01, 78.5, 152.35]}>
                    <group
                      name="Grosor_Superior_Lengueta_low"
                      position={[0, 25.42, -42]}
                    >
                      <mesh
                        name="Grosor_Superior_Lengueta_low_lambert5_0"
                        geometry={
                          nodes.Grosor_Superior_Lengueta_low_lambert5_0.geometry
                        }
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="lengueta_low" position={[0.02, -0.77, 0.93]}>
                      <mesh
                        material-color={props.color}
                        name="lengueta_low_lambert11_0"
                        geometry={nodes.lengueta_low_lambert11_0.geometry}
                        material={materials.lambert11}
                      />
                    </group>
                  </group>
                  <group
                    name="flexi_plantilla1"
                    position={[0, 0, 132.28]}
                    scale={[0.93, 1, 1]}
                  >
                    <mesh
                      name="flexi_plantilla1_lambert10_0"
                      geometry={nodes.flexi_plantilla1_lambert10_0.geometry}
                      material={materials.lambert10}
                    />
                  </group>
                  <group
                    name="plantilla_1"
                    position={[0, 0, 132.28]}
                    scale={[0.93, 1, 1]}
                  >
                    <mesh
                      material-color={props.color}
                      name="plantilla_1_lambert15_0"
                      geometry={nodes.plantilla_1_lambert15_0.geometry}
                      material={materials.lambert15}
                    />
                  </group>
                  <group
                    name="plantilla_3"
                    position={[0, 0, 132.28]}
                    scale={[0.93, 1, 1]}
                  >
                    <mesh
                      name="plantilla_3_lambert7_0"
                      geometry={nodes.plantilla_3_lambert7_0.geometry}
                      material={materials.lambert7}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload(`${window.location.hostname.substring(0,9) === "localhost" ? '/' : '/ThreeJS/'}shoes_test.glb`);

export default Shoe;
